name: add deployment status1


on:
#   pull_request:
#     types: [opened]
  push:
    branches:
    - main

jobs:
  add_deployment_status:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
          node-version: '12'
    - run: npm install @actions/core @actions/github
    - run: node --version
    - run: node .github/workflows/add_deployment_status.js
