name: add deployment status

on:
  pull_request:
    types: [closed, opened]

jobs:
  add_deployment_status:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
          node-version: '14'
    - run: npm install @actions/core @actions/github
    - run: node .github/workflows/add_deployment_status.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          test 2
